// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OYASAR.CodeGenerator.Lib.TextTemplate
{
    using OYASAR.CodeGenerator.Lib.TextTemplateModel;
    using OYASAR.CodeGenerator.Lib.TemplateManager;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ArchitectureTemplate : ArchitectureTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 8 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
 Architecture model =  ArchitectureManager.Data; 
            
            #line default
            #line hidden
            this.Write("\r\n@echo off\r\n\r\ntitle OYASAR SLN ENVIRONMENT GENERATOR\r\necho \"# <====== OYASAR SLN" +
                    " ENVIRONMENT GENERATOR ======>\"\r\n\r\nmkdir Projects\r\ncd Projects\r\n\r\nmkdir OYASAR.");
            
            #line 18 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write("\r\ncd OYASAR.");
            
            #line 19 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nmkdir OYASAR.");
            
            #line 21 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core\r\ncd OYASAR.");
            
            #line 22 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core\r\ndotnet new classlib\r\ndotnet add package oyasar.framework.core\r\ndel Class1." +
                    "cs \r\nmkdir Base\r\nmkdir Dto\r\nmkdir Model\r\nmkdir Service\r\ncd ..\r\n\r\nmkdir OYASAR.");
            
            #line 32 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Business\r\ncd OYASAR.");
            
            #line 33 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Business\r\ndotnet new classlib\r\ndotnet add reference ../OYASAR.");
            
            #line 35 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core/OYASAR.");
            
            #line 35 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.csproj\r\ndel Class1.cs\r\ncd ..\r\n\r\nmkdir OYASAR.");
            
            #line 39 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository\r\ncd OYASAR.");
            
            #line 40 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository\r\ndotnet new classlib\r\ndotnet add reference ../OYASAR.");
            
            #line 42 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core/OYASAR.");
            
            #line 42 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.csproj\r\ndel Class1.cs\r\nmkdir Base\r\nmkdir DbContext\r\nmkdir Model\r\ncd ..\r\n\r\nm" +
                    "kdir OYASAR.");
            
            #line 49 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository\r\ncd OYASAR.");
            
            #line 50 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository\r\ndotnet new classlib\r\ndotnet add reference ../OYASAR.");
            
            #line 52 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository/OYASAR.");
            
            #line 52 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository.csproj\r\ndotnet add package oyasar.framework.utils\r\ndel Class1.cs" +
                    "\r\nmkdir Base\r\nmkdir Mapping\r\ncd ..\r\n\r\nmkdir OYASAR.");
            
            #line 59 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.");
            
            #line 59 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write("\r\ncd OYASAR.");
            
            #line 60 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.");
            
            #line 60 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write("\r\ndotnet new classlib\r\ndotnet add reference ../OYASAR.");
            
            #line 62 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository/OYASAR.");
            
            #line 62 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository.csproj\r\ndotnet add package Microsoft.EntityFrameworkCore -v 2.0." +
                    "1\r\ndotnet add package Microsoft.EntityFrameworkCore.SqlServer -v 1.1.5\r\ndel Clas" +
                    "s1.cs\r\nmkdir DbContext\r\ncd ..\r\n\r\nmkdir OYASAR.");
            
            #line 69 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Api\r\ncd OYASAR.");
            
            #line 70 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Api\r\ndotnet new webapi\r\ndotnet add reference ../OYASAR.");
            
            #line 72 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core/OYASAR.");
            
            #line 72 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.csproj\r\ndotnet add reference ../OYASAR.");
            
            #line 73 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository/OYASAR.");
            
            #line 73 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.csproj\r\ndotnet add reference ../OYASAR.");
            
            #line 74 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Business/OYASAR.");
            
            #line 74 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Business.csproj\r\ndotnet add reference ../OYASAR.");
            
            #line 75 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.");
            
            #line 75 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write("/OYASAR.");
            
            #line 75 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.");
            
            #line 75 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write(".csproj\r\ndotnet add package OYASAR.Framework.");
            
            #line 76 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.IOC.Name));
            
            #line default
            #line hidden
            this.Write("\r\ndotnet add package Microsoft.AspNetCore.All -v 2.0.3\r\ndotnet add package Micros" +
                    "oft.VisualStudio.Web.CodeGeneration.Design -v 2.0.1\r\ndotnet add package oyasar.f" +
                    "ramework.");
            
            #line 79 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Mapper.Name));
            
            #line default
            #line hidden
            this.Write("\r\ndotnet add package oyasar.framework.");
            
            #line 80 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write("\r\ncd ..\r\n\r\ndotnet new sln\r\ndotnet sln add OYASAR.");
            
            #line 84 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core/OYASAR.");
            
            #line 84 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.csproj\r\ndotnet sln add OYASAR.");
            
            #line 85 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository/OYASAR.");
            
            #line 85 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Core.Repository.csproj\r\ndotnet sln add OYASAR.");
            
            #line 86 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository/OYASAR.");
            
            #line 86 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.csproj\r\ndotnet sln add OYASAR.");
            
            #line 87 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.");
            
            #line 87 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write("/OYASAR.");
            
            #line 87 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Repository.");
            
            #line 87 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ORM.Name));
            
            #line default
            #line hidden
            this.Write(".csproj\r\ndotnet sln add OYASAR.");
            
            #line 88 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Business/OYASAR.");
            
            #line 88 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Business.csproj\r\ndotnet sln add OYASAR.");
            
            #line 89 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Api/OYASAR.");
            
            #line 89 "C:\Users\Odmsn\Source\Repos\oyasar.codegenerator\OYASAR.CodeGenerator.Lib\TextTemplate\ArchitectureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.ProjectName));
            
            #line default
            #line hidden
            this.Write(".Api.csproj\r\n\r\ndotnet restore\r\ndotnet build\r\n\r\npause\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ArchitectureTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
